import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Link } from "@chakra-ui/react";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by Dashboard" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h4 className={styles.title}>Click The link below</h4>
        <Link href="/dashboard"> Launch app</Link>
      </main>

      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/logo.png" alt="Vercel Logo" width={12} height={16} />
        </span>
      </footer>
    </div>
  );
}
